version: '3.8'
services:
  web:
   build: .
   ports:
     - "5000:5000"
   environment:
     - PORT=5000
     - SECRET_KEY=karigar_setu_production_sih_2026_secret
     - DATABASE_URL=postgresql://karigar:setu2026@postgres:5432/carigarsetudb
   depends_on:
     - postgres
     - redis

 postgres:
   image: postgres:15-alpine
   environment:
     POSTGRES_USER: karigar
     POSTGRES_PASSWORD: setu2026
     POSTGRES_DB: karigarsetudb
   ports:
     - "5432:5432"

 redis:
   image: redis:7-alpine
   ports:
     - "6379:6379"
